Controllers/RecommendationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GroupF.Data;
using GroupF.Models;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using GroupF.Areas.Identity;

namespace GroupF.Controllers
{

    /*
     *  The RecommendationController handles requests required to form a list of recommended games for a particular user,
     *  determined based on game playtime and overall user rating.
     */
    public class RecommendationController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<GameUser> _signInManager;
        private readonly UserManager<GameUser> _userManager;
        private const int MAX_NEW_RATINGS = 20;

        public RecommendationController(ApplicationDbContext context, SignInManager<GameUser> signInManager, UserManager<GameUser> userManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        // GET: Recommendation
        public async Task<IActionResult> Index()
        {
            return View(await _context.GameInfoPlus.ToListAsync());
        }

        // GET: Recommendation/Details/5
        [Authorize]
        public async Task<IActionResult> Recommendations()
        {
             string steamUserName = (await _userManager.GetUserAsync(User)).SteamUsername;
            // get a Steam API Key using your login and 127.0.0.1 as your Domain Name: steamcommunity.com/dev/apikey

            ViewData["steamUserName"] = steamUserName;

            var recommendations = await GetRecommendations(steamUserName);

            ViewData["gameList"] = recommendations;

            return View(recommendations);

        }

        public async Task<IActionResult> PopulateDatabase(String steamUserName = null,int maxNewRatings = MAX_NEW_RATINGS)
        {
            ViewData["CurrentRatingsCount"] = (await _context.Rating.ToListAsync()).Count; 
            if (steamUserName == null)
                return View();

            String apiKey = Environment.GetEnvironmentVariable("Steam_API_Key");
            var httpClient = new HttpClient();

            ViewData["steamUserName"] = steamUserName;
            long steamId = 0;
            if (!long.TryParse(string.Format("{0}", steamUserName), out steamId))
            {
                steamId = await GetSteamIdFromUserName(apiKey, steamUserName, httpClient);
            }
            
            List<GameInfo> gameList = await ParseGetOwnedGamesAsync(apiKey, steamId, httpClient);
            if(gameList == null)
            {
                ViewData["GamesAdded"] = 0;
                return View();
            }
            ViewData["GamesAdded"] = await AddGameInfoToDatabase(gameList,maxNewRatings);
            ViewData["CurrentRatingsCount"] = (await _context.Rating.ToListAsync()).Count;
            return View();

        }

        public async Task<List<GameInfoPlus>> GetRecommendations(string steamUserName,bool addToDatabase = true)
        {
            String apiKey = Environment.GetEnvironmentVariable("Steam_API_Key");

            // create new HttpClient for sending and receiving information via Http protocol
            var httpClient = new HttpClient();
            
            String userName = steamUserName;

            long steamId;

            // treat the incoming input as a SteamID if it is successfully parsed to a long
            if (!long.TryParse(string.Format("{0}", userName), out steamId))
            {
                steamId = await GetSteamIdFromUserName(apiKey, userName, httpClient);
            }

            List<GameInfo> gameList = await ParseGetOwnedGamesAsync(apiKey, steamId, httpClient);

            // create list of all games to be populated, as well as a list for storing recommendations
            List<GameInfoPlus> gameInfoPlusList = new List<GameInfoPlus>();
            List<GameInfoPlus> recommendations = new List<GameInfoPlus>();

            if (steamId == 0 || gameList.Count == 0 || gameList == null)
            {
                return null;
            }
            else
            {
                if(addToDatabase)
                await AddGameInfoToDatabase(gameList);

                foreach (var game in gameList)
                {
                    // check database for rating on current game
                    Rating rating = _context.Rating.Find(game.appid);

                    if (rating != null)//get every game in the database that the player owns and we have information for
                    {
                        if (rating.likePercentage > 0 && game.playtime_forever < (4 * 60))
                        {
                            gameInfoPlusList.Add(new GameInfoPlus(game, rating));
                        }
                    }
                }

                // Sort remaining list by rating
                gameInfoPlusList.Sort(new CompareByRatingDescending());

                // listCount will determine the maximum number of items in the recommendations list
                int listCount = 20;

                if (gameInfoPlusList.Count < listCount)
                {
                    listCount = gameInfoPlusList.Count;
                }

                for (int i = 0; i < listCount; i++)
                {

                    recommendations.Add(gameInfoPlusList[i]);

                }
            }
            return recommendations;
        }

        public async Task<List<GameInfo>> ParseGetOwnedGamesAsync(String apiKey, long steamId, HttpClient client)
        {

            // the GetOwnedGames method returns a list of appids and details for each application owned by the user
            String queryString = "http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=" + apiKey + "&include_appinfo=true&steamid=" + steamId + "&format=json";

            using (var response = await client.GetAsync(queryString))
            {
                // read response as a String and parse to Json
                String apiResponse = await response.Content.ReadAsStringAsync();

                if (response.IsSuccessStatusCode)
                {
                    //// test JsonConvert Deserializer
                    dynamic parsedResponse = JsonConvert.DeserializeObject<dynamic>(apiResponse);

                    List<GameInfo> allGames = new List<GameInfo>();

                    if (parsedResponse.response.game_count >= 1)
                    {
                        Console.WriteLine("Games were found.");

                        foreach (var game in parsedResponse.response.games)
                        {
                            GameInfo tempGame = JsonConvert.DeserializeObject<GameInfo>(game.ToString());

                            allGames.Add(tempGame);
                        }
                    }
                    else
                    {
                        Console.WriteLine("No games found or profile is marked private.");
                    }

                    return allGames;
                }
                else
                {
                    Console.WriteLine("Response was null, check UserName and API key");
                    return null;
                }
            }
        }

        public async Task<long> GetSteamIdFromUserName(String apiKey, String userName, HttpClient client)
        {

            // ResolveVanityURL can be used to get the SteamID from a user with a custom URL.  Unfortunately
            // this is the only way to get a SteamID from a user without using a partner/developer API Key
            String queryString = "http://api.steampowered.com/ISteamUser/ResolveVanityURL/v1/?key=" + apiKey + "&vanityUrl=" + userName;

            using (var response = await client.GetAsync(queryString))
            {
                // read response as a String and parse to Json
                String apiResponse = await response.Content.ReadAsStringAsync();

                if (response.IsSuccessStatusCode)
                {
                    // parse apiResponse to JSON using dynamic object allocation
                    dynamic parsedResponse = JsonConvert.DeserializeObject<dynamic>(apiResponse);

                    if (parsedResponse != null && parsedResponse.response.success == 1)
                    {
                        long userId = parsedResponse.response.steamid;
                        return userId;
                    }
                    else
                    {
                        Console.WriteLine("No Steam user with username: " + userName + " found.");
                        return 0;
                    }
                }
                else
                {
                    Console.WriteLine("Api Key or Steam Username incorrect");
                    return 0;
                }

            }
        }

        // TODO: WIP method, using a highly restricted API call that made it difficult to gather substantial information on games in a reliable fashion
        // after review we opted to use the GetGameRating method below for this purpose.  This could still potentially be worked
        // into something, so it's still here.
        public async Task<List<GameInfo>> GetAppInfoFromListAsync(List<GameInfo> allGames, HttpClient client)
        {
            String queryString;
            StringBuilder str = new StringBuilder();

            for (int i = 0; i < 20; i++)
            {
                str.Append(allGames[i].appid.ToString());
                if (i != 19)
                {
                    str.Append(", ");
                }
                else
                {
                    // str.Append();
                }

Views/Shared/_HowToFindAccountInfo.cshtml
    <div class="card bg-blackblue border-dark text-white">
        <h2 class="card-header">To locate your <span class="text-steamIdandVanity">Steam Vanity Url</span> or <span class="text-steamIdandVanity">Steam Id</span></h2>
        <div class="card-body">
            <ol class="">
                <li>Naviagte to <a target="_blank" href="https://steamcommunity.com/">steamcommunity.com</a></li>
                <li>Log in to your profile</li>
                <li>Navigate to view my profile</li>
                <li>
                    Find your <span class="text-steamIdandVanity">Steam Vanity Url</span> or <span class="text-steamIdandVanity">Steam Id</span> in the last part of the url.<br />
                    <img src="~/Images/CaptureSteamWebUrl.PNG" />
                    <p class="">The <span class="text-danger">X's</span> are where you will find your <span class="text-steamIdandVanity">Steam Vanity Url</span> or <span class="text-steamIdandVanity">Steam Id</span></p>
                </li>
            </ol>
        </div>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GroupF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custom.css" />
</head>
<body class="bg-radial-gradient text-white">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-blackblue border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Steam Guilt Machine</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Recommendation" asp-action="Recommendations">(Get Recommendations)</a>
                        </li>
                    </ul>

                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">


            @RenderBody()


        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - GroupF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>